"""คำอธิบาย Use Case (เนื้อหาเดียวกับตารางที่ตรวจแล้ว) ใช้สร้าง 01-use-case.md และ 01-use-case.pdf"""

UC = [
 dict(id="UC01", name="Register account (สมัครสมาชิก)", actor="Visitor",
  desc="ผู้เยี่ยมชมสร้างบัญชีใหม่ และระบบล็อกอินให้ทันที",
  pre=["ยังไม่ได้ล็อกอิน"],
  main=["ผู้เยี่ยมชมกรอกชื่อที่แสดง อีเมล และรหัสผ่าน", "หน้าเว็บส่ง `POST /api/v1/auth/register`", "ระบบสร้างบัญชีและโปรไฟล์", "หน้าเว็บล็อกอินให้ผู้เยี่ยมชมโดยอัตโนมัติ (UC02)"],
  alt=["อีเมลนี้ถูกใช้แล้ว → 409", "ไม่กรอกชื่อ อีเมลไม่ถูกต้อง หรือรหัสผ่านไม่ได้ยาว 6–72 ตัวอักษร → 400 พร้อม `fieldErrors`"],
  post=["มีแถวใน `users` + `user_profiles` และเก็บรหัสผ่านเป็น BCrypt hash"]),
 dict(id="UC02", name="Log in (เข้าสู่ระบบ)", actor="Visitor",
  desc="ผู้เยี่ยมชมเข้าสู่ระบบด้วยอีเมลและรหัสผ่าน แล้วได้ session",
  pre=["มีบัญชีอยู่แล้ว"],
  main=["ผู้เยี่ยมชมส่งอีเมล + รหัสผ่านไปที่ `/login`", "ระบบสร้าง session", "ระบบพาไปที่ `/films`"],
  alt=["อีเมลหรือรหัสผ่านผิด → `/login?error`", "ยังไม่มีแนวหนังที่ชอบ → `/onboarding` (UC04)"],
  post=["ตั้งค่า session cookie แล้ว"]),
 dict(id="UC03", name="Log out (ออกจากระบบ)", actor="Member",
  desc="สมาชิกจบ session ปัจจุบัน",
  pre=["ล็อกอินอยู่"],
  main=["สมาชิกเปิดเมนูนำทางแล้วเลือกออกจากระบบ (`POST /logout`)"],
  alt=["—"],
  post=["session สิ้นสุด และพาไปที่ `/login?logout`"]),
 dict(id="UC04", name="Pick favorite genres (เลือกแนวหนังที่ชอบ)", actor="Member",
  desc="สมาชิกเลือกแนวหนังที่ระบบจะใช้แนะนำหนัง",
  pre=["ล็อกอินอยู่"],
  main=["สมาชิกติ๊กเลือกแนวหนัง", "หน้าเว็บส่ง `PUT /api/v1/users/me/favorite-genres`"],
  alt=["ไม่ได้ติ๊กเลย → 400 \"Pick at least one genre\"", "เลือกเกิน 10 แนว → 400"],
  post=["ข้อมูลใน `user_favorite_genres` ถูกแทนที่ด้วยชุดใหม่"]),
 dict(id="UC05", name="Browse discovery shelves (ดูชั้นหนังหน้าแรก)", actor="Member",
  desc="สมาชิกดูชั้นหนังต่าง ๆ ในหน้าแรก",
  pre=["ล็อกอินอยู่"],
  main=["สมาชิกเปิด `/films`", "ระบบแสดงหนังที่กำลังฉาย หนังที่จะเข้าฉาย หนังคะแนนสูงสุด และหนังแนะนำ (`/api/v1/movies/now-showing`, `/upcoming`, `/top-rated`, `/recommended`)"],
  alt=["ยังไม่มีแนวหนังที่ชอบ → หนังแนะนำจะใช้รายการหนังคะแนนสูงสุดแทน"],
  post=["—"]),
 dict(id="UC06", name="Search & filter catalog (ค้นหาและกรองหนัง)", actor="Member",
  desc="สมาชิกค้นหาหนังในคลังด้วยข้อความและตัวกรอง",
  pre=["ล็อกอินอยู่"],
  main=["สมาชิกกำหนดข้อความ แนวหนัง ปี ทศวรรษ ฉายก่อนวันที่ คะแนนขั้นต่ำ ภาษา และการเรียงลำดับ", "หน้าเว็บส่ง `GET /api/v1/movies`", "ระบบส่งผลลัพธ์กลับมาหน้าละ 40 รายการ"],
  alt=["ไม่พบหนังที่ตรงเงื่อนไข → แสดงหน้าว่าง", "TMDB มีข้อผิดพลาด → แสดงเฉพาะผลจากฐานข้อมูลในระบบ (บันทึก warning ไว้ใน log)"],
  post=["—"]),
 dict(id="UC07", name="Import search results from TMDB (นำเข้าผลการค้นหาจาก TMDB)", actor="System (ขยายจาก UC06)",
  desc="ระหว่างการค้นหา ระบบนำเข้าหนังที่ตรงกับคำค้นจาก TMDB",
  pre=["ค้นหาด้วยข้อความยาว 2 ตัวอักษรขึ้นไป (`MovieSearchCriteria.hasText()`) อยู่ที่หน้า 0 และตั้งค่า TMDB key แล้ว"],
  main=["ระบบเรียก `TmdbMovieCatalogAdapter.search()`", "ระบบ upsert หนังที่พบโดยใช้ `tmdb_id`"],
  alt=["ติดต่อ TMDB ไม่ได้ → ดักจับ `ExternalServiceException` ไว้ แล้วค้นหาต่อตามปกติ"],
  post=["มีแถวใน `movies` ที่เพิ่มใหม่หรือถูกอัปเดต"]),
 dict(id="UC08", name="View movie details (ดูรายละเอียดหนัง)", actor="Member",
  desc="สมาชิกเปิดหน้าหนังที่มีรายละเอียดและปุ่มต่าง ๆ",
  pre=["ล็อกอินอยู่"],
  main=["สมาชิกเปิด `/movies/{id}`", "ระบบแสดงรายละเอียด นักแสดง รีวิว (UC10) และหนังที่คล้ายกัน", "หน้าเว็บแสดงปุ่มกดถูกใจ watchlist ดูแล้ว ให้คะแนน รีวิว ตั้งเตือน และ collection"],
  alt=["ไม่พบ id นี้ → 404", "หนังยังไม่เข้าฉาย → ปุ่มดูแล้ว/ให้คะแนน/รีวิวใช้ไม่ได้ แต่ปุ่มตั้งเตือนใช้ได้"],
  post=["—"]),
 dict(id="UC09", name="Refresh movie details from TMDB (อัปเดตรายละเอียดหนังจาก TMDB)", actor="System (ขยายจาก UC08)",
  desc="เมื่อรายละเอียดหนังยังไม่มีหรือเก่าเกินไป ระบบจะดึงข้อมูลใหม่จาก TMDB",
  pre=["รายละเอียดยังไม่มีหรือเก่าเกินไป และตั้งค่า TMDB key แล้ว"],
  main=["ระบบเรียก `MovieSyncService.refreshDetails()`", "ระบบอัปเดตความยาวหนัง ผู้กำกับ นักแสดง และแนวหนัง"],
  alt=["TMDB มีข้อผิดพลาด → แสดงข้อมูลเดิม"],
  post=["`details_fetched_at` ถูกอัปเดต"]),
 dict(id="UC10", name="Read movie reviews (อ่านรีวิวหนัง)", actor="Member",
  desc="สมาชิกอ่านรีวิวของหนังเรื่องหนึ่ง",
  pre=["มีหนังเรื่องนี้อยู่ในระบบ"],
  main=["หน้าเว็บส่ง `GET /api/v1/movies/{id}/reviews`", "ระบบส่งคะแนนเฉลี่ยและรีวิวกลับมา โดยรีวิวของตัวเองอยู่บนสุด"],
  alt=["ไม่พบหนังเรื่องนี้ → 404"],
  post=["—"]),
 dict(id="UC11", name="Like / unlike movie (กดถูกใจ / ยกเลิกถูกใจหนัง)", actor="Member",
  desc="สมาชิกกดถูกใจหรือยกเลิกถูกใจหนัง",
  pre=["ล็อกอินอยู่"],
  main=["สมาชิกกด ♡ → `PUT /api/v1/users/me/likes/{movieId}` ถ้ากดซ้ำ → `DELETE`"],
  alt=["ถูกใจไว้แล้ว → ไม่มีอะไรเปลี่ยน", "ไม่พบหนังเรื่องนี้ → 404"],
  post=["เพิ่มหรือลบแถวใน `liked_movies`"]),
 dict(id="UC12", name="Add / remove watchlist (เพิ่ม / ลบ watchlist)", actor="Member",
  desc="สมาชิกเพิ่มหนังเข้า watchlist หรือลบออกจาก watchlist",
  pre=["ล็อกอินอยู่"],
  main=["สมาชิกกด + → `PUT /api/v1/users/me/watchlist/{movieId}` ถ้าลบ → `DELETE`"],
  alt=["อยู่ในรายการแล้ว → ไม่มีอะไรเปลี่ยน", "ไม่พบหนังเรื่องนี้ → 404"],
  post=["เพิ่มหรือลบแถวใน `watchlist_items`"]),
 dict(id="UC13", name="Log watched movie (บันทึกหนังที่ดูแล้ว)", actor="Member",
  desc="สมาชิกบันทึกว่าดูหนังเรื่องหนึ่งแล้ว จะให้คะแนนและเขียนรีวิวด้วยก็ได้",
  pre=["ล็อกอินอยู่ และหนังเข้าฉายแล้ว"],
  main=["สมาชิกเลือกวันที่ จำนวนดาว รีวิว และสถานที่ดู", "หน้าเว็บส่ง `POST /api/v1/users/me/diary`"],
  alt=["วันที่อยู่ในอนาคต หรือหนังยังไม่เข้าฉาย → 400", "คะแนนไม่อยู่ในช่วง 1–5 → 400", "ไม่พบหนังเรื่องนี้ → 404"],
  post=["เพิ่มแถวใน `watched_movies` และเอาหนังออกจาก watchlist ถ้ามีการเขียนรีวิว จะมีการแจ้งเตือนในแอปว่า \"review added\""]),
 dict(id="UC14", name="Edit / delete diary entry (แก้ไข / ลบบันทึกไดอารี)", actor="Member",
  desc="สมาชิกแก้ไขหรือลบบันทึกในไดอารีของตัวเอง",
  pre=["บันทึกนั้นเป็นของสมาชิกคนนี้"],
  main=["สมาชิกเลือกแก้ไข → `PUT /api/v1/users/me/diary/{id}` หรือเลือกลบ → `DELETE /api/v1/users/me/diary/{id}`"],
  alt=["ใช้กฎเรื่องวันที่เหมือน UC13", "เป็นบันทึกของผู้ใช้คนอื่น → 404"],
  post=["บันทึกถูกแก้ไข (ถ้าเพิ่มรีวิวครั้งแรก → มีการแจ้งเตือน) หรือถูกลบ"]),
 dict(id="UC15", name="Browse diary calendar (ดูปฏิทินไดอารี)", actor="Member",
  desc="สมาชิกดูไดอารีของตัวเองในรูปแบบปฏิทินรายเดือน",
  pre=["ล็อกอินอยู่"],
  main=["สมาชิกเปิดตารางรายเดือนที่ `/diary` (`/diary/calendar?month=`)", "สมาชิกคลิกเลือกวัน (`/diary/day?date=`)"],
  alt=["เดือนนั้นไม่มีบันทึก → แสดงหน้าว่าง"],
  post=["—"]),
 dict(id="UC16", name="Browse library lists (ดูรายการในคลังของฉัน)", actor="Member",
  desc="สมาชิกดูรายการหนังที่ดูแล้ว watchlist และหนังที่ถูกใจ",
  pre=["ล็อกอินอยู่"],
  main=["สมาชิกเปิดหน้า `/watched`, `/watchlist` หรือ `/liked`"],
  alt=["รายการว่าง → แสดงหน้าว่าง"],
  post=["—"]),
 dict(id="UC17", name="Manage collections (จัดการ collection)", actor="Member",
  desc="สมาชิกสร้าง เปลี่ยนชื่อ และลบ collection รวมถึงเพิ่มหรือลบหนังใน collection",
  pre=["ล็อกอินอยู่"],
  main=["สร้าง เปลี่ยนชื่อ และลบผ่าน `/api/v1/users/me/collections`", "เพิ่ม/ลบหนังผ่าน `PUT`/`DELETE /{id}/movies/{movieId}`"],
  alt=["ชื่อซ้ำ (ไม่สนตัวพิมพ์เล็ก-ใหญ่) → 409", "ไม่กรอกชื่อ → 400", "ลบหนังที่ไม่ได้อยู่ใน collection → 404"],
  post=["`collections` / `collection_movies` มีการเปลี่ยนแปลง"]),
 dict(id="UC18", name="Set / change release reminder (ตั้ง / เปลี่ยนการเตือนวันเข้าฉาย)", actor="Member",
  desc="สมาชิกขอให้ระบบเตือนก่อนหนังที่กำลังจะเข้าฉาย",
  pre=["หนังยังไม่เข้าฉาย"],
  main=["สมาชิกเลือกเตือนล่วงหน้า 7 / 3 / 1 / 0 วัน และเลือกช่องทาง IN_APP หรือ EMAIL", "หน้าเว็บส่ง `PUT /api/v1/users/me/reminders/{movieId}`"],
  alt=["เลือกจำนวนวันอื่น → 400", "ไม่พบหนังเรื่องนี้ → 404", "หนังเข้าฉายแล้วหรือไม่มีวันเข้าฉาย → 400", "มีการเตือนอยู่แล้ว → ตั้งเวลาใหม่", "ถึงวันเตือนแล้ว → ส่งทันที (UC24)"],
  post=["แถวใน `reminders` มีสถานะ SCHEDULED (หรือ SENT)"]),
 dict(id="UC19", name="Cancel release reminder (ยกเลิกการเตือนวันเข้าฉาย)", actor="Member",
  desc="สมาชิกลบการเตือน",
  pre=["มีการเตือนอยู่"],
  main=["หน้าเว็บส่ง `DELETE /api/v1/users/me/reminders/{movieId}`"],
  alt=["ไม่มีการเตือน → 404"],
  post=["สถานะเป็น CANCELLED"]),
 dict(id="UC20", name="Read notifications (อ่านการแจ้งเตือน)", actor="Member",
  desc="สมาชิกอ่านการแจ้งเตือนจากเมนูรูปกระดิ่ง",
  pre=["ล็อกอินอยู่"],
  main=["กระดิ่งแสดงจำนวนที่ยังไม่อ่าน + 10 รายการล่าสุด", "เมื่อเปิดกระดิ่งตอนที่มีรายการยังไม่อ่าน → `POST /notifications/read-all`"],
  alt=["—"],
  post=["การแจ้งเตือนทั้งหมดเป็น `is_read = true`"]),
 dict(id="UC21", name="Edit profile & view stats (แก้ไขโปรไฟล์และดูสถิติ)", actor="Member",
  desc="สมาชิกแก้ไขโปรไฟล์และดูสถิติของตัวเอง",
  pre=["ล็อกอินอยู่"],
  main=["สมาชิกแก้ไขชื่อ อีเมล bio รูปโปรไฟล์ และแนวหนังที่ชอบ → `PUT /api/v1/users/me`", "หน้าโปรไฟล์แสดงข้อมูลจาก `/api/v1/users/me/stats`"],
  alt=["อีเมลถูกใช้โดยบัญชีอื่นแล้ว → 409", "ข้อมูลไม่ถูกต้อง → 400"],
  post=["`users.email` / `user_profiles` ถูกอัปเดต"]),
 dict(id="UC22", name="Sync movie catalog (ซิงก์คลังหนัง)", actor="Scheduler",
  desc="งานที่ตั้งเวลาไว้ทำให้คลังหนังในระบบตรงกับ TMDB อยู่เสมอ",
  pre=["ตั้งค่า TMDB key แล้ว"],
  main=["`MovieSyncJob` เรียก `syncGenres()` + `syncCatalog()`", "ระบบดึงหนังที่กำลังฉาย ที่จะเข้าฉาย ยอดนิยม และคะแนนสูงสุด × `sync-pages` หน้า", "ระบบ upsert หนังโดยใช้ `tmdb_id`"],
  alt=["ไม่มี key → ข้ามไปเงียบ ๆ", "TMDB มีข้อผิดพลาด → WARN \"TMDB sync skipped\""],
  post=["เพิ่ม `genres` ที่ยังไม่มี (ชื่อเดิมยังคงไว้) และ upsert `movies` กับ `movie_genres`"]),
 dict(id="UC23", name="Dispatch due reminders (ส่งการเตือนที่ถึงกำหนด)", actor="Scheduler",
  desc="งานที่ตั้งเวลาไว้ส่งการเตือนทุกรายการที่ถึงวันเตือนแล้ว",
  pre=["—"],
  main=["`ReminderJob` เรียก `dispatchDueReminders()`", "ระบบหาการเตือนสถานะ SCHEDULED ที่วันเตือน ≤ วันนี้", "ทำ UC24 กับการเตือนแต่ละรายการ"],
  alt=["งานเกิดข้อผิดพลาด → บันทึกลง log"],
  post=["การเตือนมีสถานะ SENT"]),
 dict(id="UC24", name="Deliver reminder notification (ส่งการแจ้งเตือน)", actor="System",
  desc="ระบบส่งการเตือนที่ถึงกำหนดหนึ่งรายการผ่านช่องทางที่เลือกไว้",
  pre=["การเตือนถึงกำหนดแล้ว"],
  main=["ระบบ publish `ReminderDueEvent`", "`NotificationSenderFactory.forChannel()` เลือกตัวส่ง", "ตัวส่งเรียก `send()` เพื่อส่งการแจ้งเตือน", "ระบบบันทึกแถวใน `notifications`"],
  alt=["เลือก EMAIL แต่ไม่มี mail server → ข้ามการส่งอีเมล (บันทึกลง log) แต่ยังบันทึกข้อมูลไว้"],
  post=["เพิ่มแถวใน `notifications` และการเตือนมีสถานะ SENT"]),
]
