"""Use case descriptions (same content as the audited table). Used to build 01-use-case.md and 01-use-case.pdf."""

UC = [
 dict(id="UC01", name="Register account", actor="Visitor",
  desc="A visitor creates an account and is logged in straight away.",
  pre=["Not logged in"],
  main=["Visitor enters display name, email and password.", "Page sends `POST /api/v1/auth/register`.", "System creates the account and profile.", "Page logs the visitor in automatically (UC02)."],
  alt=["Email already used → 409.", "Blank name, invalid email, or password not 6–72 characters → 400 with `fieldErrors`."],
  post=["`users` + `user_profiles` rows exist; password stored as BCrypt hash"]),
 dict(id="UC02", name="Log in", actor="Visitor",
  desc="A visitor signs in with email and password and gets a session.",
  pre=["Account exists"],
  main=["Visitor submits email + password to `/login`.", "System creates a session.", "System redirects to `/films`."],
  alt=["Wrong email/password → `/login?error`.", "No favorite genres → `/onboarding` (UC04)."],
  post=["Session cookie set"]),
 dict(id="UC03", name="Log out", actor="Member",
  desc="A member ends the current session.",
  pre=["Logged in"],
  main=["Member opens the nav menu and chooses log out (`POST /logout`)."],
  alt=["—"],
  post=["Session ended, redirect to `/login?logout`"]),
 dict(id="UC04", name="Pick favorite genres", actor="Member",
  desc="A member chooses the genres used for recommendations.",
  pre=["Logged in"],
  main=["Member ticks genres.", "Page sends `PUT /api/v1/users/me/favorite-genres`."],
  alt=["None ticked → 400 \"Pick at least one genre\".", "More than 10 → 400."],
  post=["`user_favorite_genres` replaced"]),
 dict(id="UC05", name="Browse discovery shelves", actor="Member",
  desc="A member browses the home shelves of movies.",
  pre=["Logged in"],
  main=["Member opens `/films`.", "System shows now showing, upcoming, top rated and recommended (`/api/v1/movies/now-showing`, `/upcoming`, `/top-rated`, `/recommended`)."],
  alt=["No favorite genres → recommended falls back to top rated."],
  post=["—"]),
 dict(id="UC06", name="Search & filter catalog", actor="Member",
  desc="A member searches the catalog with text and filters.",
  pre=["Logged in"],
  main=["Member sets text, genre, year, decade, released-before, min rating, language and sort.", "Page sends `GET /api/v1/movies`.", "System returns 40 results per page."],
  alt=["No match → empty state.", "TMDB error → local results only (warning logged)."],
  post=["—"]),
 dict(id="UC07", name="Import search results from TMDB", actor="System (extends UC06)",
  desc="During a search the system imports matching movies from TMDB.",
  pre=["Text query of 2+ characters (`MovieSearchCriteria.hasText()`), page 0, TMDB key set"],
  main=["`TmdbMovieCatalogAdapter.search()` is called.", "System upserts matches by `tmdb_id`."],
  alt=["TMDB unreachable → `ExternalServiceException` caught, search continues."],
  post=["New/updated `movies` rows"]),
 dict(id="UC08", name="View movie details", actor="Member",
  desc="A member opens a movie page with details and actions.",
  pre=["Logged in"],
  main=["Member opens `/movies/{id}`.", "System shows details, cast, reviews (UC10) and similar movies.", "Page shows buttons for like, watchlist, watched, rate, review, remind and collection."],
  alt=["Unknown id → 404.", "Movie not released yet → watched/rate/review disabled, remind enabled."],
  post=["—"]),
 dict(id="UC09", name="Refresh movie details from TMDB", actor="System (extends UC08)",
  desc="When details are missing or stale the system refreshes them from TMDB.",
  pre=["Details missing or stale, TMDB key set"],
  main=["`MovieSyncService.refreshDetails()` is called.", "Runtime, director, cast and genres are updated."],
  alt=["TMDB error → old data shown."],
  post=["`details_fetched_at` updated"]),
 dict(id="UC10", name="Read movie reviews", actor="Member",
  desc="A member reads the reviews of a movie.",
  pre=["Movie exists"],
  main=["Page sends `GET /api/v1/movies/{id}/reviews`.", "System returns the average rating and reviews, own review first."],
  alt=["Unknown movie → 404."],
  post=["—"]),
 dict(id="UC11", name="Like / unlike movie", actor="Member",
  desc="A member likes or unlikes a movie.",
  pre=["Logged in"],
  main=["Member presses ♡ → `PUT /api/v1/users/me/likes/{movieId}`; pressing it again → `DELETE`."],
  alt=["Already liked → no change.", "Unknown movie → 404."],
  post=["`liked_movies` row added/removed"]),
 dict(id="UC12", name="Add / remove watchlist", actor="Member",
  desc="A member adds a movie to or removes it from the watchlist.",
  pre=["Logged in"],
  main=["Member presses + → `PUT /api/v1/users/me/watchlist/{movieId}`; remove → `DELETE`."],
  alt=["Already on list → no change.", "Unknown movie → 404."],
  post=["`watchlist_items` row added/removed"]),
 dict(id="UC13", name="Log watched movie", actor="Member",
  desc="A member records that they watched a movie, with optional rating and review.",
  pre=["Logged in, movie released"],
  main=["Member picks date, stars, review and place.", "Page sends `POST /api/v1/users/me/diary`."],
  alt=["Date in the future or movie not out yet → 400.", "Rating outside 1–5 → 400.", "Unknown movie → 404."],
  post=["`watched_movies` row added; movie removed from watchlist; if a review was written, an in-app \"review added\" notification"]),
 dict(id="UC14", name="Edit / delete diary entry", actor="Member",
  desc="A member changes or deletes one of their diary entries.",
  pre=["Entry belongs to the member"],
  main=["Member chooses edit → `PUT /api/v1/users/me/diary/{id}`, or delete → `DELETE /api/v1/users/me/diary/{id}`."],
  alt=["Same date rules as UC13.", "Entry of another user → 404."],
  post=["Entry updated (first review added → notification) or removed"]),
 dict(id="UC15", name="Browse diary calendar", actor="Member",
  desc="A member browses their diary as a month calendar.",
  pre=["Logged in"],
  main=["Member opens `/diary` month grid (`/diary/calendar?month=`).", "Member clicks a day (`/diary/day?date=`)."],
  alt=["Empty month → empty state."],
  post=["—"]),
 dict(id="UC16", name="Browse library lists", actor="Member",
  desc="A member views their watched, watchlist and liked lists.",
  pre=["Logged in"],
  main=["Member opens the `/watched`, `/watchlist` or `/liked` page."],
  alt=["Empty list → empty state."],
  post=["—"]),
 dict(id="UC17", name="Manage collections", actor="Member",
  desc="A member creates, renames and deletes collections and adds or removes movies in them.",
  pre=["Logged in"],
  main=["Create, rename, delete via `/api/v1/users/me/collections`.", "Add/remove movie via `PUT`/`DELETE /{id}/movies/{movieId}`."],
  alt=["Duplicate name (case-insensitive) → 409.", "Blank name → 400.", "Removing a movie not in it → 404."],
  post=["`collections` / `collection_movies` changed"]),
 dict(id="UC18", name="Set / change release reminder", actor="Member",
  desc="A member asks to be reminded before an upcoming movie is released.",
  pre=["Movie not released yet"],
  main=["Member chooses 7 / 3 / 1 / 0 days and IN_APP or EMAIL.", "Page sends `PUT /api/v1/users/me/reminders/{movieId}`."],
  alt=["Other offset → 400.", "Unknown movie → 404.", "Movie already out or no release date → 400.", "Reminder already exists → rescheduled.", "Date already reached → delivered now (UC24)."],
  post=["`reminders` row SCHEDULED (or SENT)"]),
 dict(id="UC19", name="Cancel release reminder", actor="Member",
  desc="A member removes a reminder.",
  pre=["Reminder exists"],
  main=["Page sends `DELETE /api/v1/users/me/reminders/{movieId}`."],
  alt=["No reminder → 404."],
  post=["Status CANCELLED"]),
 dict(id="UC20", name="Read notifications", actor="Member",
  desc="A member reads their notifications from the bell menu.",
  pre=["Logged in"],
  main=["Bell shows unread count + latest 10.", "Opening the bell while there are unread items → `POST /notifications/read-all`."],
  alt=["—"],
  post=["All notifications `is_read = true`"]),
 dict(id="UC21", name="Edit profile & view stats", actor="Member",
  desc="A member edits their profile and sees their statistics.",
  pre=["Logged in"],
  main=["Member edits name, email, bio, avatar and favorite genres → `PUT /api/v1/users/me`.", "Profile page shows `/api/v1/users/me/stats`."],
  alt=["Email used by another account → 409.", "Invalid fields → 400."],
  post=["`users.email` / `user_profiles` updated"]),
 dict(id="UC22", name="Sync movie catalog", actor="Scheduler",
  desc="A scheduled job keeps the local catalog in step with TMDB.",
  pre=["TMDB key set"],
  main=["`MovieSyncJob` runs `syncGenres()` + `syncCatalog()`.", "Now playing, upcoming, popular, top rated × `sync-pages` are fetched.", "Movies are upserted by `tmdb_id`."],
  alt=["No key → skipped silently.", "TMDB error → WARN \"TMDB sync skipped\"."],
  post=["Missing `genres` added (existing names kept); `movies` and `movie_genres` upserted"]),
 dict(id="UC23", name="Dispatch due reminders", actor="Scheduler",
  desc="A scheduled job sends every reminder whose date has been reached.",
  pre=["—"],
  main=["`ReminderJob` calls `dispatchDueReminders()`.", "SCHEDULED reminders with date ≤ today are found.", "UC24 runs for each one."],
  alt=["Job error → logged."],
  post=["Reminders SENT"]),
 dict(id="UC24", name="Deliver reminder notification", actor="System",
  desc="The system delivers one due reminder through its channel.",
  pre=["Reminder due"],
  main=["Publish `ReminderDueEvent`.", "`NotificationSenderFactory.forChannel()` picks the sender.", "Sender `send()` delivers it.", "A `notifications` row is saved."],
  alt=["EMAIL without mail server → email skipped (logged), record still saved."],
  post=["`notifications` row added; reminder SENT"]),
]
