-- Reference data: TMDB genre list + a starter set of movies so the app works before the first TMDB sync.
-- The TMDB sync job (MovieSyncService) refreshes these rows and adds now-playing / upcoming titles.
INSERT INTO
    genres (id, name)
VALUES
    (28, 'Action'),
(16, 'Animation'),
(35, 'Comedy'),
(99, 'Documentary'),
(18, 'Drama'),
(14, 'Fantasy'),
    (27, 'Horror'),
(10749, 'Romance'),
(878, 'Sci-Fi'),
(53, 'Thriller'),
(12, 'Adventure'),
(80, 'Crime'),
    (10751, 'Family'),
(36, 'History'),
(10402, 'Music'),
(9648, 'Mystery'),
(10770, 'TV Movie'),
(10752, 'War'),
(37, 'Western') ON CONFLICT DO NOTHING;

INSERT INTO
    movies (
        tmdb_id,
        title,
        original_title,
        overview,
        release_date,
        runtime,
        vote_average,
        popularity,
        original_language,
        director,
        cast_names
    )
VALUES
    (
        129,
        'Spirited Away',
        '千と千尋の神隠し',
        'Stranded in a spirit-world bathhouse, ten-year-old Chihiro works to free her parents and hold on to her own name.',
        '2001-07-20',
        125,
        8.5,
        90,
        'ja',
        'Hayao Miyazaki',
        'Rumi Hiiragi, Miyu Irino, Mari Natsuki'
    ),
    (
        8392,
        'My Neighbor Totoro',
        'となりのトトロ',
        'Two sisters move to the countryside and befriend the gentle forest spirits living next door.',
        '1988-04-16',
        86,
        8.1,
        80,
        'ja',
        'Hayao Miyazaki',
        'Noriko Hidaka, Chika Sakamoto'
    ),
    (
        4935,
        'Howl''s Moving Castle',
        'ハウルの動く城',
        'Cursed into old age, Sophie finds work aboard a wandering castle run by a vain, kind-hearted wizard.',
        '2004-11-20',
        119,
        8.4,
        86,
        'ja',
        'Hayao Miyazaki',
        'Chieko Baisho, Takuya Kimura'
    ),
    (
        128,
        'Princess Mononoke',
        'もののけ姫',
        'A cursed prince is caught between an iron-making town and the forest gods fighting to survive it.',
        '1997-07-12',
        134,
        8.3,
        78,
        'ja',
        'Hayao Miyazaki',
        'Yoji Matsuda, Yuriko Ishida'
    ),
    (
        16859,
        'Kiki''s Delivery Service',
        '魔女の宅急便',
        'A thirteen-year-old witch moves to a seaside town and starts a flying delivery business.',
        '1989-07-29',
        103,
        7.8,
        70,
        'ja',
        'Hayao Miyazaki',
        'Minami Takayama, Rei Sakuma'
    ),
    (
        12429,
        'Ponyo',
        '崖の上のポニョ',
        'A goldfish princess wants to become human after falling for the boy who rescues her.',
        '2008-07-19',
        101,
        7.7,
        68,
        'ja',
        'Hayao Miyazaki',
        'Yuria Nara, Hiroki Doi'
    ),
    (
        372058,
        'Your Name.',
        '君の名は。',
        'A city boy and a country girl start waking up in each other''s bodies, until the swaps suddenly stop.',
        '2016-08-26',
        106,
        8.5,
        85,
        'ja',
        'Makoto Shinkai',
        'Ryunosuke Kamiki, Mone Kamishiraishi'
    ),
    (
        10494,
        'Perfect Blue',
        'パーフェクトブルー',
        'A pop idol turned actress loses track of what is real as a stalker shadows her new career.',
        '1997-08-05',
        81,
        8.2,
        60,
        'ja',
        'Satoshi Kon',
        'Junko Iwao, Rica Matsumoto'
    ),
    (
        4977,
        'Paprika',
        'パプリカ',
        'A stolen device lets dreams leak into the waking world, and a therapist''s alter ego gives chase.',
        '2006-11-25',
        90,
        7.7,
        58,
        'ja',
        'Satoshi Kon',
        'Megumi Hayashibara, Toru Furuya'
    ),
    (
        14836,
        'Coraline',
        'Coraline',
        'Bored in her new house, Coraline finds a tiny door to a better version of home, with a terrible price.',
        '2009-02-05',
        100,
        7.4,
        74,
        'en',
        'Henry Selick',
        'Dakota Fanning, Teri Hatcher'
    ),
    (
        324857,
        'Spider-Man: Into the Spider-Verse',
        'Spider-Man: Into the Spider-Verse',
        'Brooklyn teen Miles Morales becomes Spider-Man and meets spider-people from other dimensions.',
        '2018-12-06',
        117,
        8.4,
        82,
        'en',
        'Bob Persichetti, Peter Ramsey, Rodney Rothman',
        'Shameik Moore, Hailee Steinfeld'
    ),
    (
        10681,
        'WALL·E',
        'WALL·E',
        'A lonely trash-compacting robot follows a sleek visitor off an abandoned Earth.',
        '2008-06-22',
        98,
        8.1,
        72,
        'en',
        'Andrew Stanton',
        'Ben Burtt, Elissa Knight'
    ),
    (
        14160,
        'Up',
        'Up',
        'A widower ties balloons to his house and floats toward South America with a stowaway scout.',
        '2009-05-28',
        96,
        7.9,
        70,
        'en',
        'Pete Docter',
        'Ed Asner, Jordan Nagai'
    ),
    (
        354912,
        'Coco',
        'Coco',
        'A boy who dreams of music crosses into the Land of the Dead to find his great-great-grandfather.',
        '2017-10-27',
        105,
        8.2,
        76,
        'en',
        'Lee Unkrich',
        'Anthony Gonzalez, Gael García Bernal'
    ),
    (
        493922,
        'Hereditary',
        'Hereditary',
        'After the family matriarch dies, her daughter''s household starts to unravel in terrifying ways.',
        '2018-06-07',
        127,
        7.3,
        76,
        'en',
        'Ari Aster',
        'Toni Collette, Alex Wolff, Milly Shapiro'
    ),
    (
        530385,
        'Midsommar',
        'Midsommar',
        'A grieving woman joins her boyfriend at a Swedish midsummer festival that is not what it seems.',
        '2019-07-03',
        148,
        7.1,
        70,
        'en',
        'Ari Aster',
        'Florence Pugh, Jack Reynor'
    ),
    (
        419430,
        'Get Out',
        'Get Out',
        'A weekend meeting his girlfriend''s parents turns into a fight to get out of their house.',
        '2017-02-24',
        104,
        7.6,
        74,
        'en',
        'Jordan Peele',
        'Daniel Kaluuya, Allison Williams'
    ),
    (
        138843,
        'The Conjuring',
        'The Conjuring',
        'Paranormal investigators Ed and Lorraine Warren help a family haunted by a dark presence in their farmhouse.',
        '2013-07-18',
        112,
        7.5,
        80,
        'en',
        'James Wan',
        'Vera Farmiga, Patrick Wilson'
    ),
    (
        426063,
        'Nosferatu',
        'Nosferatu',
        'A young wife in 1830s Germany is haunted by an ancient vampire who has fixed his attention on her.',
        '2024-12-25',
        133,
        6.7,
        78,
        'en',
        'Robert Eggers',
        'Lily-Rose Depp, Bill Skarsgård, Nicholas Hoult'
    ),
    (
        396535,
        'Train to Busan',
        '부산행',
        'A father and daughter board a train to Busan just as a zombie outbreak sweeps the country.',
        '2016-07-20',
        118,
        7.8,
        72,
        'ko',
        'Yeon Sang-ho',
        'Gong Yoo, Ma Dong-seok, Jung Yu-mi'
    ),
    (
        447332,
        'A Quiet Place',
        'A Quiet Place',
        'A family lives in total silence to hide from creatures that hunt by sound.',
        '2018-04-03',
        90,
        7.4,
        70,
        'en',
        'John Krasinski',
        'Emily Blunt, John Krasinski'
    ),
    (
        1417,
        'Pan''s Labyrinth',
        'El laberinto del fauno',
        'In 1944 Spain, a girl escapes her cruel stepfather by following a faun into a labyrinth of trials.',
        '2006-10-11',
        118,
        7.8,
        66,
        'es',
        'Guillermo del Toro',
        'Ivana Baquero, Sergi López'
    ),
    (
        120,
        'The Lord of the Rings: The Fellowship of the Ring',
        'The Lord of the Rings: The Fellowship of the Ring',
        'A quiet hobbit inherits a ring of terrible power and sets out to destroy it.',
        '2001-12-18',
        179,
        8.4,
        84,
        'en',
        'Peter Jackson',
        'Elijah Wood, Ian McKellen, Viggo Mortensen'
    ),
    (
        673,
        'Harry Potter and the Prisoner of Azkaban',
        'Harry Potter and the Prisoner of Azkaban',
        'Harry''s third year at Hogwarts brings an escaped prisoner, a new teacher and a lot of dementors.',
        '2004-05-31',
        141,
        8,
        82,
        'en',
        'Alfonso Cuarón',
        'Daniel Radcliffe, Emma Watson, Rupert Grint'
    ),
    (
        545611,
        'Everything Everywhere All at Once',
        'Everything Everywhere All at Once',
        'A laundromat owner in the middle of a tax audit must save the multiverse with her many other selves.',
        '2022-03-24',
        140,
        7.8,
        74,
        'en',
        'Daniel Kwan, Daniel Scheinert',
        'Michelle Yeoh, Ke Huy Quan, Stephanie Hsu'
    ),
    (
        693134,
        'Dune: Part Two',
        'Dune: Part Two',
        'Paul Atreides joins the Fremen and moves toward a war he has already seen in his visions.',
        '2024-02-27',
        167,
        8.2,
        88,
        'en',
        'Denis Villeneuve',
        'Timothée Chalamet, Zendaya, Austin Butler'
    ),
    (
        157336,
        'Interstellar',
        'Interstellar',
        'With Earth dying, a pilot leaves his children to search for a new home through a wormhole.',
        '2014-11-05',
        169,
        8.4,
        90,
        'en',
        'Christopher Nolan',
        'Matthew McConaughey, Anne Hathaway, Jessica Chastain'
    ),
    (
        872585,
        'Oppenheimer',
        'Oppenheimer',
        'The story of J. Robert Oppenheimer and the weapon that changed the world.',
        '2023-07-19',
        181,
        8.1,
        82,
        'en',
        'Christopher Nolan',
        'Cillian Murphy, Emily Blunt, Robert Downey Jr.'
    ),
    (
        76341,
        'Mad Max: Fury Road',
        'Mad Max: Fury Road',
        'Imperator Furiosa smuggles five women out of a tyrant''s citadel, with Max along for the ride.',
        '2015-05-13',
        121,
        7.6,
        72,
        'en',
        'George Miller',
        'Tom Hardy, Charlize Theron'
    ),
    (
        496243,
        'Parasite',
        '기생충',
        'A struggling family slowly works its way into the lives of a wealthy household, one job at a time.',
        '2019-05-30',
        132,
        8.5,
        86,
        'ko',
        'Bong Joon Ho',
        'Song Kang-ho, Choi Woo-shik, Park So-dam'
    ),
    (
        670,
        'Oldboy',
        '올드보이',
        'Released after fifteen years of unexplained captivity, a man has five days to find out why.',
        '2003-11-21',
        120,
        8.2,
        62,
        'ko',
        'Park Chan-wook',
        'Choi Min-sik, Yoo Ji-tae'
    ),
    (
        313369,
        'La La Land',
        'La La Land',
        'A jazz pianist and an aspiring actress fall in love while chasing their dreams in Los Angeles.',
        '2016-11-29',
        128,
        7.9,
        80,
        'en',
        'Damien Chazelle',
        'Ryan Gosling, Emma Stone'
    ),
    (
        194,
        'Amélie',
        'Le Fabuleux Destin d''Amélie Poulain',
        'A shy Parisian waitress secretly arranges small joys for the people around her.',
        '2001-04-25',
        122,
        7.9,
        68,
        'fr',
        'Jean-Pierre Jeunet',
        'Audrey Tautou, Mathieu Kassovitz'
    ),
    (
        76,
        'Before Sunrise',
        'Before Sunrise',
        'Two strangers meet on a train and spend one night walking and talking through Vienna.',
        '1995-01-27',
        101,
        7.9,
        56,
        'en',
        'Richard Linklater',
        'Ethan Hawke, Julie Delpy'
    ),
    (
        11104,
        'In the Mood for Love',
        '花樣年華',
        'Two neighbors in 1962 Hong Kong discover their spouses are having an affair and grow close themselves.',
        '2000-09-29',
        98,
        8.1,
        58,
        'zh',
        'Wong Kar-wai',
        'Tony Leung Chiu-wai, Maggie Cheung'
    ),
    (
        244786,
        'Whiplash',
        'Whiplash',
        'A young drummer pushes himself to the edge under a brutally demanding music teacher.',
        '2014-10-10',
        107,
        8.4,
        76,
        'en',
        'Damien Chazelle',
        'Miles Teller, J.K. Simmons'
    ),
    (
        37165,
        'The Truman Show',
        'The Truman Show',
        'An insurance salesman slowly realizes his entire life is a television show.',
        '1998-06-04',
        103,
        8.2,
        72,
        'en',
        'Peter Weir',
        'Jim Carrey, Laura Linney'
    ),
    (
        38,
        'Eternal Sunshine of the Spotless Mind',
        'Eternal Sunshine of the Spotless Mind',
        'After a painful breakup, a man has his ex erased from his memory and regrets it halfway through.',
        '2004-03-19',
        108,
        8.1,
        70,
        'en',
        'Michel Gondry',
        'Jim Carrey, Kate Winslet'
    ),
    (
        120467,
        'The Grand Budapest Hotel',
        'The Grand Budapest Hotel',
        'A legendary concierge and his lobby boy get caught up in the theft of a priceless painting.',
        '2014-02-26',
        99,
        8,
        70,
        'en',
        'Wes Anderson',
        'Ralph Fiennes, Tony Revolori'
    ) ON CONFLICT DO NOTHING;

INSERT INTO
    movie_genres (movie_id, genre_id)
SELECT
    m.id,
    v.genre_id
FROM
    (
        VALUES
            (129, 16),
            (129, 14),
            (8392, 16),
            (8392, 14),
            (4935, 16),
            (4935, 14),
            (4935, 10749),
            (128, 16),
            (128, 14),
            (128, 28),
            (16859, 16),
            (16859, 14),
            (12429, 16),
            (12429, 14),
            (372058, 16),
            (372058, 10749),
            (372058, 18),
            (10494, 16),
            (10494, 53),
            (4977, 16),
            (4977, 878),
            (4977, 14),
            (14836, 16),
            (14836, 14),
            (14836, 27),
            (324857, 16),
            (324857, 28),
            (324857, 878),
            (10681, 16),
            (10681, 878),
            (14160, 16),
            (14160, 35),
            (354912, 16),
            (354912, 14),
            (493922, 27),
            (493922, 18),
            (530385, 27),
            (530385, 18),
            (419430, 27),
            (419430, 53),
            (138843, 27),
            (138843, 53),
            (426063, 27),
            (426063, 14),
            (396535, 27),
            (396535, 28),
            (447332, 27),
            (447332, 878),
            (1417, 14),
            (1417, 18),
            (120, 14),
            (120, 28),
            (673, 14),
            (545611, 878),
            (545611, 35),
            (545611, 28),
            (693134, 878),
            (693134, 28),
            (157336, 878),
            (157336, 18),
            (872585, 18),
            (76341, 28),
            (76341, 878),
            (496243, 53),
            (496243, 35),
            (496243, 18),
            (670, 53),
            (670, 18),
            (313369, 10749),
            (313369, 18),
            (194, 10749),
            (194, 35),
            (76, 10749),
            (76, 18),
            (11104, 10749),
            (11104, 18),
            (244786, 18),
            (37165, 35),
            (37165, 18),
            (38, 10749),
            (38, 878),
            (120467, 35)
    ) AS v(tmdb_id, genre_id)
    JOIN movies m ON m.tmdb_id = v.tmdb_id ON CONFLICT DO NOTHING;